version: '3'
services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: sehsekou98
      POSTGRES_PASSWORD: passworl1
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:
